# Generated by Django 3.1.5 on 2021-01-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20210122_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
