# Generated by Django 3.1.5 on 2021-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
