# Generated by Django 3.1.5 on 2021-01-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_auto_20210125_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='image',
        ),
    ]
