# Generated by Django 3.1.5 on 2021-01-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_auto_20210125_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
